### PR TITLE
Add a Dockerfile for building a container image

### PR DESCRIPTION
**Pull request by jihchi**
> Inspired by https://github.com/ekzhang/bore/issues/6#issuecomment-1094206675.

Furthermore, It would be convenient to provide bore image in public registry (e.g. [Docker Hub](https://hub.docker.com/), [Github Packages Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry)) such that people can immediately pull and run it in cloud/container environments.

### Build image

```console
$ docker build -t bore .
```

### Launch a container (e.g. a bore server)

```console
$ docker run bore --port 7835:7835 server
2022-04-10T08:30:32.286590Z  INFO bore_cli::server: server listening addr=0.0.0.0:7835
```

### Image Size

```console
REPOSITORY      TAG       IMAGE ID       CREATED          SIZE
bore            latest    8f459317dfed   15 minutes ago   75.1MB
```

### CODE REVIEW

**Comment by praveenperera** [comment]
@jihchi What about an alpine build for a tiny docker image?

**Comment by jihchi** [comment]
@praveenperera sounds good to me but it is probably good to have a separate Dockerfile for alpine-based image? at least we'd need to compile bore with musl support?

**Comment by praveenperera** [comment]
Sounds good I can make another PR with an alpine based Dockerimage

**Comment by ekzhang** [comment]
Thanks for the contribution! I love how simple the `cargo install --path .` is. Agree with @praveenperera though that I don't see a benefit to using buster for something like this — it would work just as well with a `rust:alpine` tag and `alpine:latest` image, and probably be smaller (although 75 MB isn't bad!)?

(Actually with [another application](https://github.com/ekzhang/rustpad/blob/main/Dockerfile) I've made, it seemed like it was possible to just copy a `rust:alpine` built image directly into `scratch` and avoid OS image files entirely. It will statically link to `musl-dev` if that is present. That image is <6 MB. But `alpine` is very small too; it doesn't really make a difference to me whether `alpine` or `scratch` is used.)

Happy to add a CI step on each tagged release to push a `latest` and versioned tag in a public Docker registry like `docker.io/ekzhang/bore`.

**Comment by jihchi** [comment]
@ekzhang  Alright, thanks for the reference, it is quite simple to switch to musl-based image and the size of image goes down to ~**6**MB.

```
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
bore         latest    3de2027d23f3   19 minutes ago   6.09MB
```

**Comment by ekzhang** [comment]
I added `/target` to the `.dockerignore` so that it wouldn't send gigabytes of build context, and I also added a CI job that runs on releases to publish to DockerHub. Thanks for your contribution!

**Pull request merged**
