### PR TITLE
Expose local port as env value

### LINKED ISSUE #131: Feature Request: Configure local port via environment variable
Firstly, thanks for bore, it's awesome.

I'm using it to forward some ports to a server which is behind a NAT. We wrapped the whole thing in a systemd config, big thanks to #36. It would be sweet if we could configure the port like `PORT=XXX` in the env file. :-)

### PR DESCRIPTION
**Pull request by archer884**
Noticed the request in #131 and realized it's like... one line. Closes #131.

### CODE REVIEW

**Comment by ekzhang** [comment]
Thanks!

**Comment by ekzhang** [comment]
Ah drat, CI is broken. Sorry do you know how to fix this 😅

**Comment by archer884** [comment]
lol no. It's been a minute, but I'll take a look.

**Comment by archer884** [comment]
Looks like it's using an outdated job ... definition... thing? Man, I totally get why devops is a whole job these days...

image

**Pull request merged**
